### ISSUE TITLE
Crash when no VMs are in Hyper-V

### ISSUE THREAD

**Issue by 0xf005ba11** [0xf005ba11/vmplex-ws#39] opened 2023-04-14 03:09 UTC
![image](https://user-images.githubusercontent.com/56487417/231931657-86e2351f-7a77-44de-8af5-e71a44b1d32e.png)

**Comment by jxy-s** [comment] 2023-04-14 03:24
From twitter thread: https://twitter.com/MouriNaruto/status/1646704801403772928?s=20

> I have tried several versions of VMPlex in GitHub Releases, I found it cannot show the VM which is created in VMPlex GUI after I restart the VMPlex process. Also, I found VMPlex will crash when no VMs in Hyper-V or using Hyper-V Manager to remove VMs.

![image](https://user-images.githubusercontent.com/11687482/231933623-c1a2e893-b097-4d20-8548-02953d3e6fc8.png)

> Additional crash information for launching clean VMPlex instance (extracted from the release zip package) when no VMs in Hyper-V.

![image](https://user-images.githubusercontent.com/11687482/231933647-87b6f5d9-baf2-4fd7-8fa0-1ea3d6e72a8a.png)

**Comment by MouriNaruto** [comment] 2023-04-14 03:39
I will subscribe this issue and hope it to be resolved.

Kenji Mouri

**Comment by jxy-s** [comment] 2023-04-14 04:03
@MouriNaruto I was able to reproduce the crash. The above fix should resolve it.

> I found VMPlex will crash when no VMs in Hyper-V or using Hyper-V Manager to remove VMs.

This should be resolved with https://github.com/0xf005ba11/vmplex-ws/pull/41

> I found it cannot show the VM which is created in VMPlex GUI after I restart the VMPlex process.

I could not reproduce this. Could you provide more detailed steps to reproduce?

**Comment by MouriNaruto** [comment] 2023-04-14 04:08
@jxy-s I have tested the main branch. The issue (I found VMPlex will crash when no VMs in Hyper-V or using Hyper-V Manager to remove VMs.) is resolved.

![image](https://user-images.githubusercontent.com/10867563/231938854-e002601d-cbec-471d-98f2-599a4f8f92c7.png)

For that issue (I found it cannot show the VM which is created in VMPlex GUI after I restart the VMPlex process.), I will provide more information because I found I met an exception shown in  Visual Studio debugger when creating a VM via VMPlex. Please wait. I will reply that information to this issue.

Kenji Mouri

**Comment by jxy-s** [comment] 2023-04-14 04:13
Thank you Kenji! ❤️ - I appreciate you verifying the fix. I look forward to your analysis. If you know where the problem is, feel free to put up a PR to address it.

**Comment by MouriNaruto** [comment] 2023-04-14 04:15
@jxy-s 

I found I met an exception shown in Visual Studio debugger when creating a VM via VMPlex.
```
Exception thrown: 'System.InvalidOperationException' in WindowsBase.dll
An exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll but was not handled in user code
```

Here is the video.

[2023-04-14 12-11-01.zip](https://github.com/0xf005ba11/vmplex-ws/files/11228704/2023-04-14.12-11-01.zip)

Kenji Mouri

**Comment by jxy-s** [comment] 2023-04-14 04:22
Thanks for the details and video. My guess is maybe this is a localization issue? Based on your previous screenshot it seems like there is no VM showing up in the Hyper-V manager either. Is that still the case? Also, if you create the VM through the Hyper-V manager does it show up in VMPlex?

**Comment by MouriNaruto** [comment] 2023-04-14 04:30
@jxy-s 

> Based on your previous screenshot it seems like there is no VM showing up in the Hyper-V manager either.

That screenshot is for validating the issue (I found VMPlex will crash when no VMs in Hyper-V or using Hyper-V Manager to remove VMs.) is fixed.

Here is the screenshot for "I found it cannot show the VM which is created in VMPlex GUI after I restart the VMPlex process.":

![image](https://user-images.githubusercontent.com/10867563/231942064-424eaaaa-e6c5-421d-81ef-d70e2fdd1108.png)

> Also, if you create the VM through the Hyper-V manager does it show up in VMPlex?

I tried create a VM via VMPlex because the VMs created by Hyper-V Manager will not show up in VMPlex.

Kenji Mouri

**Comment by jxy-s** [comment] 2023-04-14 04:46
👍 thanks for clarifying. When you encounter that exception (from the video, could you capture a dump file (`Debug > Save dump as...`)? If you do, please send me that dump file _including the symbol files_. You may email me if you can't upload it here (johnny.shaw@live.com).

**Comment by jxy-s** [comment] 2023-04-14 15:09
@MouriNaruto thanks for digging in to this ❤️ . We will investigate if there is an alternative. cc @0xf005ba11

**Comment by jxy-s** [comment] 2023-04-14 17:27
The purpose of that list is to filter out the host systems from the list (`"Hosting Computer System"`, `"Hosting Computer System"`). Looking over the alternatives:
1. `InstallDate` looks to be `{1/1/0001 12:00:00 AM}` for the host system (similarly for other dates in the object).
2. `EnhancedSessionModeState` looks to maybe be an erroneous/undocumented value (is set to `0`):
```c#
        public enum EnhancedSessionMode : ushort
        {
            AllowedAndAvailable = 2,
            NotAllowed = 3,
            AllowedButUnavailable = 6
        }
```

**Closed** 2023-04-14 23:13 UTC
Labels: bug

**Comment by jxy-s** [comment] 2023-04-14 23:15
@MouriNaruto a fix was merged that should address the issue you were having. Please let us know if the issue continues.

**Comment by MouriNaruto** [comment] 2023-04-15 15:25
@jxy-s 

![image](https://user-images.githubusercontent.com/10867563/232233975-2969f869-6343-4921-a500-9a65a1a9adc3.png)

I have confirmed that issue has been fixed.

Kenji Mouri
